### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test tap-fleetio

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        pip install poetry
    - name: Install dependencies
      run: |
        poetry install
      env:
        TAP_FLEETIO_API_TOKEN: {{ secrets.TAP_FLEETIO_API_TOKEN }}
        TAP_FLEETIO_ACCOUNT_TOKEN: {{ secrets.TAP_FLEETIO_ACCOUNT_TOKEN }}
    - name: Test with pytest
      run: |
        poetry run pytest
